type AuditLog {
  id: String!
  timestamp: String!
  type: Int!
  action_user_id: String!
  action_user: UserPartial
  target: AuditLogTarget!
  changes: [AuditLogChange!]!
  reason: String
}

type AuditLogTarget {
  id: String!
  data: String!
  type: String!
}

type AuditLogChange {
  key: String!
  values: [String!]!
}
