extend type Mutation {
  createCosmeticPaint(definition: CosmeticPaintInput!): ObjectID!
    @hasPermissions(role: [MANAGE_COSMETICS])

  cosmetics(id: ObjectID!): CosmeticOps!
}

type CosmeticOps {
  id: ObjectID!
  updatePaint(definition: CosmeticPaintInput!): CosmeticPaint!
    @goField(forceResolver: true)
    @hasPermissions(role: [MANAGE_COSMETICS])
}

extend type Query {
  cosmetics(list: [ObjectID!]): CosmeticsQuery!
}

type CosmeticsQuery {
  paints: [CosmeticPaint!]!
  badges: [CosmeticBadge!]!
}

interface Cosmetic {
  id: ObjectID!
  kind: CosmeticKind!
  name: String!
}

type CosmeticBadge implements Cosmetic {
  id: ObjectID!
  kind: CosmeticKind!
  name: String!
  tooltip: String!
  tag: String!
  host: ImageHost!
}

type CosmeticPaint implements Cosmetic {
  id: ObjectID!
  kind: CosmeticKind!
  name: String!

  function: CosmeticPaintFunction!
  color: Int
  angle: Int!
  shape: String
  image_url: String
  repeat: Boolean!
  stops: [CosmeticPaintStop!]!
  shadows: [CosmeticPaintShadow!]!
}

type CosmeticPaintStop {
  at: Float!
  color: Int!
}

type CosmeticPaintShadow {
  x_offset: Float!
  y_offset: Float!
  radius: Float!
  color: Int!
}

enum CosmeticKind {
  BADGE
  PAINT
}

enum CosmeticPaintFunction {
  LINEAR_GRADIENT
  RADIAL_GRADIENT
  URL
}

input CosmeticPaintInput {
  name: String!
  function: CosmeticPaintFunction!
  color: Int
  angle: Int
  shape: String
  image_url: String
  repeat: Boolean!
  stops: [CosmeticPaintStopInput!]!
  shadows: [CosmeticPaintShadowInput!]!
}

input CosmeticPaintStopInput {
  at: Float!
  color: Int!
}
input CosmeticPaintShadowInput {
  x_offset: Float!
  y_offset: Float!
  radius: Float!
  color: Int!
}
