type Image {
  name: String!
  format: ImageFormat!
  width: Int!
  height: Int!
  frame_count: Int!
  size: Int!
}

enum ImageFormat {
  AVIF
  WEBP
  GIF
  PNG
}

type ImageHost {
  url: String!
  files(formats: [ImageFormat!]): [Image!]! @goField(forceResolver: true)
}

type Archive {
  name: String!
  content_type: String!
  url: String!
  size: Int!
}
