extend type Mutation {
  sendActivity(
    status: ActivityStatus!
    type: ActivityTypeInput
    object: ActivityObjectInput
  ): ObjectID!
}

extend type Query {
  onlineUsers: [UserPartial!]!
}

type Activity {
  user_id: ObjectID!
  user: User!
  name: String!
  type: ActivityType!
  status: ActivityStatus!
}

enum ActivityStatus {
  OFFLINE
  IDLE
  DND
  ONLINE
}

enum ActivityType {
  VIEWING
  EDITING
  WATCHING
  LISTENING
  CHATTING
  CREATING
  UPDATING
}

type ActivityTimespan {
  start: Time!
  end: Time!
}

input ActivityTypeInput {
  name: String!
  type: ActivityType!
}

input ActivityObjectInput {
  kind: Int!
  id: ObjectID!
}
