directive @hasPermissions(
  role: [Permission!]
) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

enum Permission {
  CREATE_EMOTE
  EDIT_EMOTE
  CREATE_EMOTE_SET
  EDIT_EMOTE_SET

  CREATE_REPORT
  SEND_MESSAGES

  FEATURE_ZEROWIDTH_EMOTE_TYPE
  FEATURE_PROFILE_PICTURE_ANIMATION

  MANAGE_BANS
  MANAGE_ROLES
  MANAGE_REPORTS
  MANAGE_USERS
  EDIT_ANY_EMOTE
  EDIT_ANY_EMOTE_SET
  BYPASS_PRIVACY

  SUPER_ADMINISTRATOR
  MANAGE_NEWS
  MANAGE_STACK
  MANAGE_COSMETICS
}
